name: Publish Release
on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "10"
      - name: yarn Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --force
      - name: Build and Pre-Publish
        run: yarn vscode:prepublish
      - name: Install VSCE
        run: yarn add vsce
      - name: Publish
        run: yarn vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
